const city = [
    {
        "addrCodeId":"110000",
        "addrName":"北京市",
        "addrFullname":"北京市",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"110100",
                "addrName":"市辖区",
                "addrFullname":"北京市市辖区",
                "addrType":1
            },
            {
                "addrCodeId":"110200",
                "addrName":"县",
                "addrFullname":"北京市县",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"120000",
        "addrName":"天津市",
        "addrFullname":"天津市",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"120100",
                "addrName":"市辖区",
                "addrFullname":"天津市市辖区",
                "addrType":1
            },
            {
                "addrCodeId":"120200",
                "addrName":"县",
                "addrFullname":"天津市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"130000",
        "addrName":"河北省",
        "addrFullname":"河北省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"130100",
                "addrName":"石家庄市",
                "addrFullname":"河北省石家庄市",
                "addrType":1
            },
            {
                "addrCodeId":"130200",
                "addrName":"唐山市",
                "addrFullname":"河北省唐山市",
                "addrType":1
            },
            {
                "addrCodeId":"130300",
                "addrName":"秦皇岛市",
                "addrFullname":"河北省秦皇岛市",
                "addrType":1
            },
            {
                "addrCodeId":"130400",
                "addrName":"邯郸市",
                "addrFullname":"河北省邯郸市",
                "addrType":1
            },
            {
                "addrCodeId":"130500",
                "addrName":"邢台市",
                "addrFullname":"河北省邢台市",
                "addrType":1
            },
            {
                "addrCodeId":"130600",
                "addrName":"保定市",
                "addrFullname":"河北省保定市",
                "addrType":1
            },
            {
                "addrCodeId":"130700",
                "addrName":"张家口市",
                "addrFullname":"河北省张家口市",
                "addrType":1
            },
            {
                "addrCodeId":"130800",
                "addrName":"承德市",
                "addrFullname":"河北省承德市",
                "addrType":1
            },
            {
                "addrCodeId":"130900",
                "addrName":"沧州市",
                "addrFullname":"河北省沧州市",
                "addrType":1
            },
            {
                "addrCodeId":"131000",
                "addrName":"廊坊市",
                "addrFullname":"河北省廊坊市",
                "addrType":1
            },
            {
                "addrCodeId":"131100",
                "addrName":"衡水市",
                "addrFullname":"河北省衡水市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"140000",
        "addrName":"山西省",
        "addrFullname":"山西省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"140100",
                "addrName":"太原市",
                "addrFullname":"山西省太原市",
                "addrType":1
            },
            {
                "addrCodeId":"140200",
                "addrName":"大同市",
                "addrFullname":"山西省大同市",
                "addrType":1
            },
            {
                "addrCodeId":"140300",
                "addrName":"阳泉市",
                "addrFullname":"山西省阳泉市",
                "addrType":1
            },
            {
                "addrCodeId":"140400",
                "addrName":"长治市",
                "addrFullname":"山西省长治市",
                "addrType":1
            },
            {
                "addrCodeId":"140500",
                "addrName":"晋城市",
                "addrFullname":"山西省晋城市",
                "addrType":1
            },
            {
                "addrCodeId":"140600",
                "addrName":"朔州市",
                "addrFullname":"山西省朔州市",
                "addrType":1
            },
            {
                "addrCodeId":"140700",
                "addrName":"晋中市",
                "addrFullname":"山西省晋中市",
                "addrType":1
            },
            {
                "addrCodeId":"140800",
                "addrName":"运城市",
                "addrFullname":"山西省运城市",
                "addrType":1
            },
            {
                "addrCodeId":"140900",
                "addrName":"忻州市",
                "addrFullname":"山西省忻州市",
                "addrType":1
            },
            {
                "addrCodeId":"141000",
                "addrName":"临汾市",
                "addrFullname":"山西省临汾市",
                "addrType":1
            },
            {
                "addrCodeId":"141100",
                "addrName":"吕梁市",
                "addrFullname":"山西省吕梁市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"150000",
        "addrName":"内蒙古自治区",
        "addrFullname":"内蒙古自治区",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"150100",
                "addrName":"呼和浩特市",
                "addrFullname":"内蒙古自治区呼和浩特市",
                "addrType":1
            },
            {
                "addrCodeId":"150200",
                "addrName":"包头市",
                "addrFullname":"内蒙古自治区包头市",
                "addrType":1
            },
            {
                "addrCodeId":"150300",
                "addrName":"乌海市",
                "addrFullname":"内蒙古自治区乌海市",
                "addrType":1
            },
            {
                "addrCodeId":"150400",
                "addrName":"赤峰市",
                "addrFullname":"内蒙古自治区赤峰市",
                "addrType":1
            },
            {
                "addrCodeId":"150500",
                "addrName":"通辽市",
                "addrFullname":"内蒙古自治区通辽市",
                "addrType":1
            },
            {
                "addrCodeId":"150600",
                "addrName":"鄂尔多斯市",
                "addrFullname":"内蒙古自治区鄂尔多斯市",
                "addrType":1
            },
            {
                "addrCodeId":"150700",
                "addrName":"呼伦贝尔市",
                "addrFullname":"内蒙古自治区呼伦贝尔市",
                "addrType":1
            },
            {
                "addrCodeId":"150800",
                "addrName":"巴彦淖尔市",
                "addrFullname":"内蒙古自治区巴彦淖尔市",
                "addrType":1
            },
            {
                "addrCodeId":"150900",
                "addrName":"乌兰察布市",
                "addrFullname":"内蒙古自治区乌兰察布市",
                "addrType":1
            },
            {
                "addrCodeId":"152200",
                "addrName":"兴安盟",
                "addrFullname":"内蒙古自治区兴安盟",
                "addrType":1
            },
            {
                "addrCodeId":"152500",
                "addrName":"锡林郭勒盟",
                "addrFullname":"内蒙古自治区锡林郭勒盟",
                "addrType":1
            },
            {
                "addrCodeId":"152900",
                "addrName":"阿拉善盟",
                "addrFullname":"内蒙古自治区阿拉善盟",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"210000",
        "addrName":"辽宁省",
        "addrFullname":"辽宁省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"210100",
                "addrName":"沈阳市",
                "addrFullname":"辽宁省沈阳市",
                "addrType":1
            },
            {
                "addrCodeId":"210200",
                "addrName":"大连市",
                "addrFullname":"辽宁省大连市",
                "addrType":1
            },
            {
                "addrCodeId":"210300",
                "addrName":"鞍山市",
                "addrFullname":"辽宁省鞍山市",
                "addrType":1
            },
            {
                "addrCodeId":"210400",
                "addrName":"抚顺市",
                "addrFullname":"辽宁省抚顺市",
                "addrType":1
            },
            {
                "addrCodeId":"210500",
                "addrName":"本溪市",
                "addrFullname":"辽宁省本溪市",
                "addrType":1
            },
            {
                "addrCodeId":"210600",
                "addrName":"丹东市",
                "addrFullname":"辽宁省丹东市",
                "addrType":1
            },
            {
                "addrCodeId":"210700",
                "addrName":"锦州市",
                "addrFullname":"辽宁省锦州市",
                "addrType":1
            },
            {
                "addrCodeId":"210800",
                "addrName":"营口市",
                "addrFullname":"辽宁省营口市",
                "addrType":1
            },
            {
                "addrCodeId":"210900",
                "addrName":"阜新市",
                "addrFullname":"辽宁省阜新市",
                "addrType":1
            },
            {
                "addrCodeId":"211000",
                "addrName":"辽阳市",
                "addrFullname":"辽宁省辽阳市",
                "addrType":1
            },
            {
                "addrCodeId":"211100",
                "addrName":"盘锦市",
                "addrFullname":"辽宁省盘锦市",
                "addrType":1
            },
            {
                "addrCodeId":"211200",
                "addrName":"铁岭市",
                "addrFullname":"辽宁省铁岭市",
                "addrType":1
            },
            {
                "addrCodeId":"211300",
                "addrName":"朝阳市",
                "addrFullname":"辽宁省朝阳市",
                "addrType":1
            },
            {
                "addrCodeId":"211400",
                "addrName":"葫芦岛市",
                "addrFullname":"辽宁省葫芦岛市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"220000",
        "addrName":"吉林省",
        "addrFullname":"吉林省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"220100",
                "addrName":"长春市",
                "addrFullname":"吉林省长春市",
                "addrType":1
            },
            {
                "addrCodeId":"220200",
                "addrName":"吉林市",
                "addrFullname":"吉林省吉林市",
                "addrType":1
            },
            {
                "addrCodeId":"220300",
                "addrName":"四平市",
                "addrFullname":"吉林省四平市",
                "addrType":1
            },
            {
                "addrCodeId":"220400",
                "addrName":"辽源市",
                "addrFullname":"吉林省辽源市",
                "addrType":1
            },
            {
                "addrCodeId":"220500",
                "addrName":"通化市",
                "addrFullname":"吉林省通化市",
                "addrType":1
            },
            {
                "addrCodeId":"220600",
                "addrName":"白山市",
                "addrFullname":"吉林省白山市",
                "addrType":1
            },
            {
                "addrCodeId":"220700",
                "addrName":"松原市",
                "addrFullname":"吉林省松原市",
                "addrType":1
            },
            {
                "addrCodeId":"220800",
                "addrName":"白城市",
                "addrFullname":"吉林省白城市",
                "addrType":1
            },
            {
                "addrCodeId":"222400",
                "addrName":"延边朝鲜族自治州",
                "addrFullname":"吉林省延边朝鲜族自治州",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"230000",
        "addrName":"黑龙江省",
        "addrFullname":"黑龙江省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"230100",
                "addrName":"哈尔滨市",
                "addrFullname":"黑龙江省哈尔滨市",
                "addrType":1
            },
            {
                "addrCodeId":"230200",
                "addrName":"齐齐哈尔市",
                "addrFullname":"黑龙江省齐齐哈尔市",
                "addrType":1
            },
            {
                "addrCodeId":"230300",
                "addrName":"鸡西市",
                "addrFullname":"黑龙江省鸡西市",
                "addrType":1
            },
            {
                "addrCodeId":"230400",
                "addrName":"鹤岗市",
                "addrFullname":"黑龙江省鹤岗市",
                "addrType":1
            },
            {
                "addrCodeId":"230500",
                "addrName":"双鸭山市",
                "addrFullname":"黑龙江省双鸭山市",
                "addrType":1
            },
            {
                "addrCodeId":"230600",
                "addrName":"大庆市",
                "addrFullname":"黑龙江省大庆市",
                "addrType":1
            },
            {
                "addrCodeId":"230700",
                "addrName":"伊春市",
                "addrFullname":"黑龙江省伊春市",
                "addrType":1
            },
            {
                "addrCodeId":"230800",
                "addrName":"佳木斯市",
                "addrFullname":"黑龙江省佳木斯市",
                "addrType":1
            },
            {
                "addrCodeId":"230900",
                "addrName":"七台河市",
                "addrFullname":"黑龙江省七台河市",
                "addrType":1
            },
            {
                "addrCodeId":"231000",
                "addrName":"牡丹江市",
                "addrFullname":"黑龙江省牡丹江市",
                "addrType":1
            },
            {
                "addrCodeId":"231100",
                "addrName":"黑河市",
                "addrFullname":"黑龙江省黑河市",
                "addrType":1
            },
            {
                "addrCodeId":"231200",
                "addrName":"绥化市",
                "addrFullname":"黑龙江省绥化市",
                "addrType":1
            },
            {
                "addrCodeId":"232700",
                "addrName":"大兴安岭地区",
                "addrFullname":"黑龙江省大兴安岭地区",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"310000",
        "addrName":"上海市",
        "addrFullname":"上海市",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"310100",
                "addrName":"市辖区",
                "addrFullname":"上海市",
                "addrType":1
            },
            {
                "addrCodeId":"310200",
                "addrName":"县",
                "addrFullname":"上海市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"320000",
        "addrName":"江苏省",
        "addrFullname":"江苏省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"320100",
                "addrName":"南京市",
                "addrFullname":"江苏省南京市",
                "addrType":1
            },
            {
                "addrCodeId":"320200",
                "addrName":"无锡市",
                "addrFullname":"江苏省无锡市",
                "addrType":1
            },
            {
                "addrCodeId":"320300",
                "addrName":"徐州市",
                "addrFullname":"江苏省徐州市",
                "addrType":1
            },
            {
                "addrCodeId":"320400",
                "addrName":"常州市",
                "addrFullname":"江苏省常州市",
                "addrType":1
            },
            {
                "addrCodeId":"320500",
                "addrName":"苏州市",
                "addrFullname":"江苏省苏州市",
                "addrType":1
            },
            {
                "addrCodeId":"320600",
                "addrName":"南通市",
                "addrFullname":"江苏省南通市",
                "addrType":1
            },
            {
                "addrCodeId":"320700",
                "addrName":"连云港市",
                "addrFullname":"江苏省连云港市",
                "addrType":1
            },
            {
                "addrCodeId":"320800",
                "addrName":"淮安市",
                "addrFullname":"江苏省淮安市",
                "addrType":1
            },
            {
                "addrCodeId":"320900",
                "addrName":"盐城市",
                "addrFullname":"江苏省盐城市",
                "addrType":1
            },
            {
                "addrCodeId":"321000",
                "addrName":"扬州市",
                "addrFullname":"江苏省扬州市",
                "addrType":1
            },
            {
                "addrCodeId":"321100",
                "addrName":"镇江市",
                "addrFullname":"江苏省镇江市",
                "addrType":1
            },
            {
                "addrCodeId":"321200",
                "addrName":"泰州市",
                "addrFullname":"江苏省泰州市",
                "addrType":1
            },
            {
                "addrCodeId":"321300",
                "addrName":"宿迁市",
                "addrFullname":"江苏省宿迁市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"330000",
        "addrName":"浙江省",
        "addrFullname":"浙江省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"330100",
                "addrName":"杭州市",
                "addrFullname":"浙江省杭州市",
                "addrType":1
            },
            {
                "addrCodeId":"330200",
                "addrName":"宁波市",
                "addrFullname":"浙江省宁波市",
                "addrType":1
            },
            {
                "addrCodeId":"330300",
                "addrName":"温州市",
                "addrFullname":"浙江省温州市",
                "addrType":1
            },
            {
                "addrCodeId":"330400",
                "addrName":"嘉兴市",
                "addrFullname":"浙江省嘉兴市",
                "addrType":1
            },
            {
                "addrCodeId":"330500",
                "addrName":"湖州市",
                "addrFullname":"浙江省湖州市",
                "addrType":1
            },
            {
                "addrCodeId":"330600",
                "addrName":"绍兴市",
                "addrFullname":"浙江省绍兴市",
                "addrType":1
            },
            {
                "addrCodeId":"330700",
                "addrName":"金华市",
                "addrFullname":"浙江省金华市",
                "addrType":1
            },
            {
                "addrCodeId":"330800",
                "addrName":"衢州市",
                "addrFullname":"浙江省衢州市",
                "addrType":1
            },
            {
                "addrCodeId":"330900",
                "addrName":"舟山市",
                "addrFullname":"浙江省舟山市",
                "addrType":1
            },
            {
                "addrCodeId":"331000",
                "addrName":"台州市",
                "addrFullname":"浙江省台州市",
                "addrType":1
            },
            {
                "addrCodeId":"331100",
                "addrName":"丽水市",
                "addrFullname":"浙江省丽水市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"340000",
        "addrName":"安徽省",
        "addrFullname":"安徽省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"340100",
                "addrName":"合肥市",
                "addrFullname":"安徽省合肥市",
                "addrType":1
            },
            {
                "addrCodeId":"340200",
                "addrName":"芜湖市",
                "addrFullname":"安徽省芜湖市",
                "addrType":1
            },
            {
                "addrCodeId":"340300",
                "addrName":"蚌埠市",
                "addrFullname":"安徽省蚌埠市",
                "addrType":1
            },
            {
                "addrCodeId":"340400",
                "addrName":"淮南市",
                "addrFullname":"安徽省淮南市",
                "addrType":1
            },
            {
                "addrCodeId":"340500",
                "addrName":"马鞍山市",
                "addrFullname":"安徽省马鞍山市",
                "addrType":1
            },
            {
                "addrCodeId":"340600",
                "addrName":"淮北市",
                "addrFullname":"安徽省淮北市",
                "addrType":1
            },
            {
                "addrCodeId":"340700",
                "addrName":"铜陵市",
                "addrFullname":"安徽省铜陵市",
                "addrType":1
            },
            {
                "addrCodeId":"340800",
                "addrName":"安庆市",
                "addrFullname":"安徽省安庆市",
                "addrType":1
            },
            {
                "addrCodeId":"341000",
                "addrName":"黄山市",
                "addrFullname":"安徽省黄山市",
                "addrType":1
            },
            {
                "addrCodeId":"341100",
                "addrName":"滁州市",
                "addrFullname":"安徽省滁州市",
                "addrType":1
            },
            {
                "addrCodeId":"341200",
                "addrName":"阜阳市",
                "addrFullname":"安徽省阜阳市",
                "addrType":1
            },
            {
                "addrCodeId":"341300",
                "addrName":"宿州市",
                "addrFullname":"安徽省宿州市",
                "addrType":1
            },
            {
                "addrCodeId":"341400",
                "addrName":"巢湖市",
                "addrFullname":"安徽省巢湖市",
                "addrType":1
            },
            {
                "addrCodeId":"341500",
                "addrName":"六安市",
                "addrFullname":"安徽省六安市",
                "addrType":1
            },
            {
                "addrCodeId":"341600",
                "addrName":"亳州市",
                "addrFullname":"安徽省亳州市",
                "addrType":1
            },
            {
                "addrCodeId":"341700",
                "addrName":"池州市",
                "addrFullname":"安徽省池州市",
                "addrType":1
            },
            {
                "addrCodeId":"341800",
                "addrName":"宣城市",
                "addrFullname":"安徽省宣城市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"350000",
        "addrName":"福建省",
        "addrFullname":"福建省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"350100",
                "addrName":"福州市",
                "addrFullname":"福建省福州市",
                "addrType":1
            },
            {
                "addrCodeId":"350200",
                "addrName":"厦门市",
                "addrFullname":"福建省厦门市",
                "addrType":1
            },
            {
                "addrCodeId":"350300",
                "addrName":"莆田市",
                "addrFullname":"福建省莆田市",
                "addrType":1
            },
            {
                "addrCodeId":"350400",
                "addrName":"三明市",
                "addrFullname":"福建省三明市",
                "addrType":1
            },
            {
                "addrCodeId":"350500",
                "addrName":"泉州市",
                "addrFullname":"福建省泉州市",
                "addrType":1
            },
            {
                "addrCodeId":"350600",
                "addrName":"漳州市",
                "addrFullname":"福建省漳州市",
                "addrType":1
            },
            {
                "addrCodeId":"350700",
                "addrName":"南平市",
                "addrFullname":"福建省南平市",
                "addrType":1
            },
            {
                "addrCodeId":"350800",
                "addrName":"龙岩市",
                "addrFullname":"福建省龙岩市",
                "addrType":1
            },
            {
                "addrCodeId":"350900",
                "addrName":"宁德市",
                "addrFullname":"福建省宁德市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"360000",
        "addrName":"江西省",
        "addrFullname":"江西省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"360100",
                "addrName":"南昌市",
                "addrFullname":"江西省南昌市",
                "addrType":1
            },
            {
                "addrCodeId":"360200",
                "addrName":"景德镇市",
                "addrFullname":"江西省景德镇市",
                "addrType":1
            },
            {
                "addrCodeId":"360300",
                "addrName":"萍乡市",
                "addrFullname":"江西省萍乡市",
                "addrType":1
            },
            {
                "addrCodeId":"360400",
                "addrName":"九江市",
                "addrFullname":"江西省九江市",
                "addrType":1
            },
            {
                "addrCodeId":"360500",
                "addrName":"新余市",
                "addrFullname":"江西省新余市",
                "addrType":1
            },
            {
                "addrCodeId":"360600",
                "addrName":"鹰潭市",
                "addrFullname":"江西省鹰潭市",
                "addrType":1
            },
            {
                "addrCodeId":"360700",
                "addrName":"赣州市",
                "addrFullname":"江西省赣州市",
                "addrType":1
            },
            {
                "addrCodeId":"360800",
                "addrName":"吉安市",
                "addrFullname":"江西省吉安市",
                "addrType":1
            },
            {
                "addrCodeId":"360900",
                "addrName":"宜春市",
                "addrFullname":"江西省宜春市",
                "addrType":1
            },
            {
                "addrCodeId":"361000",
                "addrName":"抚州市",
                "addrFullname":"江西省抚州市",
                "addrType":1
            },
            {
                "addrCodeId":"361100",
                "addrName":"上饶市",
                "addrFullname":"江西省上饶市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"370000",
        "addrName":"山东省",
        "addrFullname":"山东省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"370100",
                "addrName":"济南市",
                "addrFullname":"山东省济南市",
                "addrType":1
            },
            {
                "addrCodeId":"370200",
                "addrName":"青岛市",
                "addrFullname":"山东省青岛市",
                "addrType":1
            },
            {
                "addrCodeId":"370300",
                "addrName":"淄博市",
                "addrFullname":"山东省淄博市",
                "addrType":1
            },
            {
                "addrCodeId":"370400",
                "addrName":"枣庄市",
                "addrFullname":"山东省枣庄市",
                "addrType":1
            },
            {
                "addrCodeId":"370500",
                "addrName":"东营市",
                "addrFullname":"山东省东营市",
                "addrType":1
            },
            {
                "addrCodeId":"370600",
                "addrName":"烟台市",
                "addrFullname":"山东省烟台市",
                "addrType":1
            },
            {
                "addrCodeId":"370700",
                "addrName":"潍坊市",
                "addrFullname":"山东省潍坊市",
                "addrType":1
            },
            {
                "addrCodeId":"370800",
                "addrName":"济宁市",
                "addrFullname":"山东省济宁市",
                "addrType":1
            },
            {
                "addrCodeId":"370900",
                "addrName":"泰安市",
                "addrFullname":"山东省泰安市",
                "addrType":1
            },
            {
                "addrCodeId":"371000",
                "addrName":"威海市",
                "addrFullname":"山东省威海市",
                "addrType":1
            },
            {
                "addrCodeId":"371100",
                "addrName":"日照市",
                "addrFullname":"山东省日照市",
                "addrType":1
            },
            {
                "addrCodeId":"371200",
                "addrName":"莱芜市",
                "addrFullname":"山东省莱芜市",
                "addrType":1
            },
            {
                "addrCodeId":"371300",
                "addrName":"临沂市",
                "addrFullname":"山东省临沂市",
                "addrType":1
            },
            {
                "addrCodeId":"371400",
                "addrName":"德州市",
                "addrFullname":"山东省德州市",
                "addrType":1
            },
            {
                "addrCodeId":"371500",
                "addrName":"聊城市",
                "addrFullname":"山东省聊城市",
                "addrType":1
            },
            {
                "addrCodeId":"371600",
                "addrName":"滨州市",
                "addrFullname":"山东省滨州市",
                "addrType":1
            },
            {
                "addrCodeId":"371700",
                "addrName":"荷泽市",
                "addrFullname":"山东省荷泽市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"410000",
        "addrName":"河南省",
        "addrFullname":"河南省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"410100",
                "addrName":"郑州市",
                "addrFullname":"河南省郑州市",
                "addrType":1
            },
            {
                "addrCodeId":"410200",
                "addrName":"开封市",
                "addrFullname":"河南省开封市",
                "addrType":1
            },
            {
                "addrCodeId":"410300",
                "addrName":"洛阳市",
                "addrFullname":"河南省洛阳市",
                "addrType":1
            },
            {
                "addrCodeId":"410400",
                "addrName":"平顶山市",
                "addrFullname":"河南省平顶山市",
                "addrType":1
            },
            {
                "addrCodeId":"410500",
                "addrName":"安阳市",
                "addrFullname":"河南省安阳市",
                "addrType":1
            },
            {
                "addrCodeId":"410600",
                "addrName":"鹤壁市",
                "addrFullname":"河南省鹤壁市",
                "addrType":1
            },
            {
                "addrCodeId":"410700",
                "addrName":"新乡市",
                "addrFullname":"河南省新乡市",
                "addrType":1
            },
            {
                "addrCodeId":"410800",
                "addrName":"焦作市",
                "addrFullname":"河南省焦作市",
                "addrType":1
            },
            {
                "addrCodeId":"410900",
                "addrName":"濮阳市",
                "addrFullname":"河南省濮阳市",
                "addrType":1
            },
            {
                "addrCodeId":"411000",
                "addrName":"许昌市",
                "addrFullname":"河南省许昌市",
                "addrType":1
            },
            {
                "addrCodeId":"411100",
                "addrName":"漯河市",
                "addrFullname":"河南省漯河市",
                "addrType":1
            },
            {
                "addrCodeId":"411200",
                "addrName":"三门峡市",
                "addrFullname":"河南省三门峡市",
                "addrType":1
            },
            {
                "addrCodeId":"411300",
                "addrName":"南阳市",
                "addrFullname":"河南省南阳市",
                "addrType":1
            },
            {
                "addrCodeId":"411400",
                "addrName":"商丘市",
                "addrFullname":"河南省商丘市",
                "addrType":1
            },
            {
                "addrCodeId":"411500",
                "addrName":"信阳市",
                "addrFullname":"河南省信阳市",
                "addrType":1
            },
            {
                "addrCodeId":"411600",
                "addrName":"周口市",
                "addrFullname":"河南省周口市",
                "addrType":1
            },
            {
                "addrCodeId":"411700",
                "addrName":"驻马店市",
                "addrFullname":"河南省驻马店市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"420000",
        "addrName":"湖北省",
        "addrFullname":"湖北省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"420100",
                "addrName":"武汉市",
                "addrFullname":"湖北省武汉市",
                "addrType":1
            },
            {
                "addrCodeId":"420200",
                "addrName":"黄石市",
                "addrFullname":"湖北省黄石市",
                "addrType":1
            },
            {
                "addrCodeId":"420300",
                "addrName":"十堰市",
                "addrFullname":"湖北省十堰市",
                "addrType":1
            },
            {
                "addrCodeId":"420500",
                "addrName":"宜昌市",
                "addrFullname":"湖北省宜昌市",
                "addrType":1
            },
            {
                "addrCodeId":"420600",
                "addrName":"襄樊市",
                "addrFullname":"湖北省襄樊市",
                "addrType":1
            },
            {
                "addrCodeId":"420700",
                "addrName":"鄂州市",
                "addrFullname":"湖北省鄂州市",
                "addrType":1
            },
            {
                "addrCodeId":"420800",
                "addrName":"荆门市",
                "addrFullname":"湖北省荆门市",
                "addrType":1
            },
            {
                "addrCodeId":"420900",
                "addrName":"孝感市",
                "addrFullname":"湖北省孝感市",
                "addrType":1
            },
            {
                "addrCodeId":"421000",
                "addrName":"荆州市",
                "addrFullname":"湖北省荆州市",
                "addrType":1
            },
            {
                "addrCodeId":"421100",
                "addrName":"黄冈市",
                "addrFullname":"湖北省黄冈市",
                "addrType":1
            },
            {
                "addrCodeId":"421200",
                "addrName":"咸宁市",
                "addrFullname":"湖北省咸宁市",
                "addrType":1
            },
            {
                "addrCodeId":"421300",
                "addrName":"随州市",
                "addrFullname":"湖北省随州市",
                "addrType":1
            },
            {
                "addrCodeId":"422800",
                "addrName":"恩施土家族苗族自治州",
                "addrFullname":"湖北省恩施土家族苗族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"429000",
                "addrName":"省直辖行政单位",
                "addrFullname":"湖北省省直辖行政单位",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"430000",
        "addrName":"湖南省",
        "addrFullname":"湖南省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"430100",
                "addrName":"长沙市",
                "addrFullname":"湖南省长沙市",
                "addrType":1
            },
            {
                "addrCodeId":"430200",
                "addrName":"株洲市",
                "addrFullname":"湖南省株洲市",
                "addrType":1
            },
            {
                "addrCodeId":"430300",
                "addrName":"湘潭市",
                "addrFullname":"湖南省湘潭市",
                "addrType":1
            },
            {
                "addrCodeId":"430400",
                "addrName":"衡阳市",
                "addrFullname":"湖南省衡阳市",
                "addrType":1
            },
            {
                "addrCodeId":"430500",
                "addrName":"邵阳市",
                "addrFullname":"湖南省邵阳市",
                "addrType":1
            },
            {
                "addrCodeId":"430600",
                "addrName":"岳阳市",
                "addrFullname":"湖南省岳阳市",
                "addrType":1
            },
            {
                "addrCodeId":"430700",
                "addrName":"常德市",
                "addrFullname":"湖南省常德市",
                "addrType":1
            },
            {
                "addrCodeId":"430800",
                "addrName":"张家界市",
                "addrFullname":"湖南省张家界市",
                "addrType":1
            },
            {
                "addrCodeId":"430900",
                "addrName":"益阳市",
                "addrFullname":"湖南省益阳市",
                "addrType":1
            },
            {
                "addrCodeId":"431000",
                "addrName":"郴州市",
                "addrFullname":"湖南省郴州市",
                "addrType":1
            },
            {
                "addrCodeId":"431100",
                "addrName":"永州市",
                "addrFullname":"湖南省永州市",
                "addrType":1
            },
            {
                "addrCodeId":"431200",
                "addrName":"怀化市",
                "addrFullname":"湖南省怀化市",
                "addrType":1
            },
            {
                "addrCodeId":"431300",
                "addrName":"娄底市",
                "addrFullname":"湖南省娄底市",
                "addrType":1
            },
            {
                "addrCodeId":"433100",
                "addrName":"湘西土家族苗族自治州",
                "addrFullname":"湖南省湘西土家族苗族自治州",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"440000",
        "addrName":"广东省",
        "addrFullname":"广东省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"440100",
                "addrName":"广州市",
                "addrFullname":"广东省广州市",
                "addrType":1
            },
            {
                "addrCodeId":"440200",
                "addrName":"韶关市",
                "addrFullname":"广东省韶关市",
                "addrType":1
            },
            {
                "addrCodeId":"440300",
                "addrName":"深圳市",
                "addrFullname":"广东省深圳市",
                "addrType":1
            },
            {
                "addrCodeId":"440400",
                "addrName":"珠海市",
                "addrFullname":"广东省珠海市",
                "addrType":1
            },
            {
                "addrCodeId":"440500",
                "addrName":"汕头市",
                "addrFullname":"广东省汕头市",
                "addrType":1
            },
            {
                "addrCodeId":"440600",
                "addrName":"佛山市",
                "addrFullname":"广东省佛山市",
                "addrType":1
            },
            {
                "addrCodeId":"440700",
                "addrName":"江门市",
                "addrFullname":"广东省江门市",
                "addrType":1
            },
            {
                "addrCodeId":"440800",
                "addrName":"湛江市",
                "addrFullname":"广东省湛江市",
                "addrType":1
            },
            {
                "addrCodeId":"440900",
                "addrName":"茂名市",
                "addrFullname":"广东省茂名市",
                "addrType":1
            },
            {
                "addrCodeId":"441200",
                "addrName":"肇庆市",
                "addrFullname":"广东省肇庆市",
                "addrType":1
            },
            {
                "addrCodeId":"441300",
                "addrName":"惠州市",
                "addrFullname":"广东省惠州市",
                "addrType":1
            },
            {
                "addrCodeId":"441400",
                "addrName":"梅州市",
                "addrFullname":"广东省梅州市",
                "addrType":1
            },
            {
                "addrCodeId":"441500",
                "addrName":"汕尾市",
                "addrFullname":"广东省汕尾市",
                "addrType":1
            },
            {
                "addrCodeId":"441600",
                "addrName":"河源市",
                "addrFullname":"广东省河源市",
                "addrType":1
            },
            {
                "addrCodeId":"441700",
                "addrName":"阳江市",
                "addrFullname":"广东省阳江市",
                "addrType":1
            },
            {
                "addrCodeId":"441800",
                "addrName":"清远市",
                "addrFullname":"广东省清远市",
                "addrType":1
            },
            {
                "addrCodeId":"441900",
                "addrName":"东莞市",
                "addrFullname":"广东省东莞市",
                "addrType":1
            },
            {
                "addrCodeId":"442000",
                "addrName":"中山市",
                "addrFullname":"广东省中山市",
                "addrType":1
            },
            {
                "addrCodeId":"445100",
                "addrName":"潮州市",
                "addrFullname":"广东省潮州市",
                "addrType":1
            },
            {
                "addrCodeId":"445200",
                "addrName":"揭阳市",
                "addrFullname":"广东省揭阳市",
                "addrType":1
            },
            {
                "addrCodeId":"445300",
                "addrName":"云浮市",
                "addrFullname":"广东省云浮市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"450000",
        "addrName":"广西壮族自治区",
        "addrFullname":"广西壮族自治区",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"450100",
                "addrName":"南宁市",
                "addrFullname":"广西壮族自治区南宁市",
                "addrType":1
            },
            {
                "addrCodeId":"450200",
                "addrName":"柳州市",
                "addrFullname":"广西壮族自治区柳州市",
                "addrType":1
            },
            {
                "addrCodeId":"450300",
                "addrName":"桂林市",
                "addrFullname":"广西壮族自治区桂林市",
                "addrType":1
            },
            {
                "addrCodeId":"450400",
                "addrName":"梧州市",
                "addrFullname":"广西壮族自治区梧州市",
                "addrType":1
            },
            {
                "addrCodeId":"450500",
                "addrName":"北海市",
                "addrFullname":"广西壮族自治区北海市",
                "addrType":1
            },
            {
                "addrCodeId":"450600",
                "addrName":"防城港市",
                "addrFullname":"广西壮族自治区防城港市",
                "addrType":1
            },
            {
                "addrCodeId":"450700",
                "addrName":"钦州市",
                "addrFullname":"广西壮族自治区钦州市",
                "addrType":1
            },
            {
                "addrCodeId":"450800",
                "addrName":"贵港市",
                "addrFullname":"广西壮族自治区贵港市",
                "addrType":1
            },
            {
                "addrCodeId":"450900",
                "addrName":"玉林市",
                "addrFullname":"广西壮族自治区玉林市",
                "addrType":1
            },
            {
                "addrCodeId":"451000",
                "addrName":"百色市",
                "addrFullname":"广西壮族自治区百色市",
                "addrType":1
            },
            {
                "addrCodeId":"451100",
                "addrName":"贺州市",
                "addrFullname":"广西壮族自治区贺州市",
                "addrType":1
            },
            {
                "addrCodeId":"451200",
                "addrName":"河池市",
                "addrFullname":"广西壮族自治区河池市",
                "addrType":1
            },
            {
                "addrCodeId":"451300",
                "addrName":"来宾市",
                "addrFullname":"广西壮族自治区来宾市",
                "addrType":1
            },
            {
                "addrCodeId":"451400",
                "addrName":"崇左市",
                "addrFullname":"广西壮族自治区崇左市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"460000",
        "addrName":"海南省",
        "addrFullname":"海南省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"460100",
                "addrName":"海口市",
                "addrFullname":"海南省海口市",
                "addrType":1
            },
            {
                "addrCodeId":"460200",
                "addrName":"三亚市",
                "addrFullname":"海南省三亚市",
                "addrType":1
            },
            {
                "addrCodeId":"469000",
                "addrName":"省直辖县级行政单位",
                "addrFullname":"海南省省直辖县级行政单位",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"500000",
        "addrName":"重庆市",
        "addrFullname":"重庆市",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"500100",
                "addrName":"市辖区",
                "addrFullname":"重庆市",
                "addrType":1
            },
            {
                "addrCodeId":"500200",
                "addrName":"县",
                "addrFullname":"重庆市",
                "addrType":1
            },
            {
                "addrCodeId":"500300",
                "addrName":"市",
                "addrFullname":"重庆市市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"510000",
        "addrName":"四川省",
        "addrFullname":"四川省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"510100",
                "addrName":"成都市",
                "addrFullname":"四川省成都市",
                "addrType":1
            },
            {
                "addrCodeId":"510300",
                "addrName":"自贡市",
                "addrFullname":"四川省自贡市",
                "addrType":1
            },
            {
                "addrCodeId":"510400",
                "addrName":"攀枝花市",
                "addrFullname":"四川省攀枝花市",
                "addrType":1
            },
            {
                "addrCodeId":"510500",
                "addrName":"泸州市",
                "addrFullname":"四川省泸州市",
                "addrType":1
            },
            {
                "addrCodeId":"510600",
                "addrName":"德阳市",
                "addrFullname":"四川省德阳市",
                "addrType":1
            },
            {
                "addrCodeId":"510700",
                "addrName":"绵阳市",
                "addrFullname":"四川省绵阳市",
                "addrType":1
            },
            {
                "addrCodeId":"510800",
                "addrName":"广元市",
                "addrFullname":"四川省广元市",
                "addrType":1
            },
            {
                "addrCodeId":"510900",
                "addrName":"遂宁市",
                "addrFullname":"四川省遂宁市",
                "addrType":1
            },
            {
                "addrCodeId":"511000",
                "addrName":"内江市",
                "addrFullname":"四川省内江市",
                "addrType":1
            },
            {
                "addrCodeId":"511100",
                "addrName":"乐山市",
                "addrFullname":"四川省乐山市",
                "addrType":1
            },
            {
                "addrCodeId":"511300",
                "addrName":"南充市",
                "addrFullname":"四川省南充市",
                "addrType":1
            },
            {
                "addrCodeId":"511400",
                "addrName":"眉山市",
                "addrFullname":"四川省眉山市",
                "addrType":1
            },
            {
                "addrCodeId":"511500",
                "addrName":"宜宾市",
                "addrFullname":"四川省宜宾市",
                "addrType":1
            },
            {
                "addrCodeId":"511600",
                "addrName":"广安市",
                "addrFullname":"四川省广安市",
                "addrType":1
            },
            {
                "addrCodeId":"511700",
                "addrName":"达州市",
                "addrFullname":"四川省达州市",
                "addrType":1
            },
            {
                "addrCodeId":"511800",
                "addrName":"雅安市",
                "addrFullname":"四川省雅安市",
                "addrType":1
            },
            {
                "addrCodeId":"511900",
                "addrName":"巴中市",
                "addrFullname":"四川省巴中市",
                "addrType":1
            },
            {
                "addrCodeId":"512000",
                "addrName":"资阳市",
                "addrFullname":"四川省资阳市",
                "addrType":1
            },
            {
                "addrCodeId":"513200",
                "addrName":"阿坝藏族羌族自治州",
                "addrFullname":"四川省阿坝藏族羌族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"513300",
                "addrName":"甘孜藏族自治州",
                "addrFullname":"四川省甘孜藏族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"513400",
                "addrName":"凉山彝族自治州",
                "addrFullname":"四川省凉山彝族自治州",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"520000",
        "addrName":"贵州省",
        "addrFullname":"贵州省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"520100",
                "addrName":"贵阳市",
                "addrFullname":"贵州省贵阳市",
                "addrType":1
            },
            {
                "addrCodeId":"520200",
                "addrName":"六盘水市",
                "addrFullname":"贵州省六盘水市",
                "addrType":1
            },
            {
                "addrCodeId":"520300",
                "addrName":"遵义市",
                "addrFullname":"贵州省遵义市",
                "addrType":1
            },
            {
                "addrCodeId":"520400",
                "addrName":"安顺市",
                "addrFullname":"贵州省安顺市",
                "addrType":1
            },
            {
                "addrCodeId":"522200",
                "addrName":"铜仁地区",
                "addrFullname":"贵州省铜仁地区",
                "addrType":1
            },
            {
                "addrCodeId":"522300",
                "addrName":"黔西南布依族苗族自治州",
                "addrFullname":"贵州省黔西南布依族苗族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"522400",
                "addrName":"毕节地区",
                "addrFullname":"贵州省毕节地区",
                "addrType":1
            },
            {
                "addrCodeId":"522600",
                "addrName":"黔东南苗族侗族自治州",
                "addrFullname":"贵州省黔东南苗族侗族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"522700",
                "addrName":"黔南布依族苗族自治州",
                "addrFullname":"贵州省黔南布依族苗族自治州",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"530000",
        "addrName":"云南省",
        "addrFullname":"云南省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"530100",
                "addrName":"昆明市",
                "addrFullname":"云南省昆明市",
                "addrType":1
            },
            {
                "addrCodeId":"530300",
                "addrName":"曲靖市",
                "addrFullname":"云南省曲靖市",
                "addrType":1
            },
            {
                "addrCodeId":"530400",
                "addrName":"玉溪市",
                "addrFullname":"云南省玉溪市",
                "addrType":1
            },
            {
                "addrCodeId":"530500",
                "addrName":"保山市",
                "addrFullname":"云南省保山市",
                "addrType":1
            },
            {
                "addrCodeId":"530600",
                "addrName":"昭通市",
                "addrFullname":"云南省昭通市",
                "addrType":1
            },
            {
                "addrCodeId":"530700",
                "addrName":"丽江市",
                "addrFullname":"云南省丽江市",
                "addrType":1
            },
            {
                "addrCodeId":"530800",
                "addrName":"思茅市",
                "addrFullname":"云南省思茅市",
                "addrType":1
            },
            {
                "addrCodeId":"530900",
                "addrName":"临沧市",
                "addrFullname":"云南省临沧市",
                "addrType":1
            },
            {
                "addrCodeId":"532300",
                "addrName":"楚雄彝族自治州",
                "addrFullname":"云南省楚雄彝族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"532500",
                "addrName":"红河哈尼族彝族自治州",
                "addrFullname":"云南省红河哈尼族彝族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"532600",
                "addrName":"文山壮族苗族自治州",
                "addrFullname":"云南省文山壮族苗族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"532800",
                "addrName":"西双版纳傣族自治州",
                "addrFullname":"云南省西双版纳傣族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"532900",
                "addrName":"大理白族自治州",
                "addrFullname":"云南省大理白族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"533100",
                "addrName":"德宏傣族景颇族自治州",
                "addrFullname":"云南省德宏傣族景颇族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"533300",
                "addrName":"怒江傈僳族自治州",
                "addrFullname":"云南省怒江傈僳族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"533400",
                "addrName":"迪庆藏族自治州",
                "addrFullname":"云南省迪庆藏族自治州",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"540000",
        "addrName":"西藏自治区",
        "addrFullname":"西藏自治区",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"540100",
                "addrName":"拉萨市",
                "addrFullname":"西藏自治区拉萨市",
                "addrType":1
            },
            {
                "addrCodeId":"542100",
                "addrName":"昌都地区",
                "addrFullname":"西藏自治区昌都地区",
                "addrType":1
            },
            {
                "addrCodeId":"542200",
                "addrName":"山南地区",
                "addrFullname":"西藏自治区山南地区",
                "addrType":1
            },
            {
                "addrCodeId":"542300",
                "addrName":"日喀则地区",
                "addrFullname":"西藏自治区日喀则地区",
                "addrType":1
            },
            {
                "addrCodeId":"542400",
                "addrName":"那曲地区",
                "addrFullname":"西藏自治区那曲地区",
                "addrType":1
            },
            {
                "addrCodeId":"542500",
                "addrName":"阿里地区",
                "addrFullname":"西藏自治区阿里地区",
                "addrType":1
            },
            {
                "addrCodeId":"542600",
                "addrName":"林芝地区",
                "addrFullname":"西藏自治区林芝地区",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"610000",
        "addrName":"陕西省",
        "addrFullname":"陕西省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"610100",
                "addrName":"西安市",
                "addrFullname":"陕西省西安市",
                "addrType":1
            },
            {
                "addrCodeId":"610200",
                "addrName":"铜川市",
                "addrFullname":"陕西省铜川市",
                "addrType":1
            },
            {
                "addrCodeId":"610300",
                "addrName":"宝鸡市",
                "addrFullname":"陕西省宝鸡市",
                "addrType":1
            },
            {
                "addrCodeId":"610400",
                "addrName":"咸阳市",
                "addrFullname":"陕西省咸阳市",
                "addrType":1
            },
            {
                "addrCodeId":"610500",
                "addrName":"渭南市",
                "addrFullname":"陕西省渭南市",
                "addrType":1
            },
            {
                "addrCodeId":"610600",
                "addrName":"延安市",
                "addrFullname":"陕西省延安市",
                "addrType":1
            },
            {
                "addrCodeId":"610700",
                "addrName":"汉中市",
                "addrFullname":"陕西省汉中市",
                "addrType":1
            },
            {
                "addrCodeId":"610800",
                "addrName":"榆林市",
                "addrFullname":"陕西省榆林市",
                "addrType":1
            },
            {
                "addrCodeId":"610900",
                "addrName":"安康市",
                "addrFullname":"陕西省安康市",
                "addrType":1
            },
            {
                "addrCodeId":"611000",
                "addrName":"商洛市",
                "addrFullname":"陕西省商洛市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"620000",
        "addrName":"甘肃省",
        "addrFullname":"甘肃省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"620100",
                "addrName":"兰州市",
                "addrFullname":"甘肃省兰州市",
                "addrType":1
            },
            {
                "addrCodeId":"620200",
                "addrName":"嘉峪关市",
                "addrFullname":"甘肃省嘉峪关市",
                "addrType":1
            },
            {
                "addrCodeId":"620300",
                "addrName":"金昌市",
                "addrFullname":"甘肃省金昌市",
                "addrType":1
            },
            {
                "addrCodeId":"620400",
                "addrName":"白银市",
                "addrFullname":"甘肃省白银市",
                "addrType":1
            },
            {
                "addrCodeId":"620500",
                "addrName":"天水市",
                "addrFullname":"甘肃省天水市",
                "addrType":1
            },
            {
                "addrCodeId":"620600",
                "addrName":"武威市",
                "addrFullname":"甘肃省武威市",
                "addrType":1
            },
            {
                "addrCodeId":"620700",
                "addrName":"张掖市",
                "addrFullname":"甘肃省张掖市",
                "addrType":1
            },
            {
                "addrCodeId":"620800",
                "addrName":"平凉市",
                "addrFullname":"甘肃省平凉市",
                "addrType":1
            },
            {
                "addrCodeId":"620900",
                "addrName":"酒泉市",
                "addrFullname":"甘肃省酒泉市",
                "addrType":1
            },
            {
                "addrCodeId":"621000",
                "addrName":"庆阳市",
                "addrFullname":"甘肃省庆阳市",
                "addrType":1
            },
            {
                "addrCodeId":"621100",
                "addrName":"定西市",
                "addrFullname":"甘肃省定西市",
                "addrType":1
            },
            {
                "addrCodeId":"621200",
                "addrName":"陇南市",
                "addrFullname":"甘肃省陇南市",
                "addrType":1
            },
            {
                "addrCodeId":"622900",
                "addrName":"临夏回族自治州",
                "addrFullname":"甘肃省临夏回族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"623000",
                "addrName":"甘南藏族自治州",
                "addrFullname":"甘肃省甘南藏族自治州",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"630000",
        "addrName":"青海省",
        "addrFullname":"青海省",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"630100",
                "addrName":"西宁市",
                "addrFullname":"青海省西宁市",
                "addrType":1
            },
            {
                "addrCodeId":"632100",
                "addrName":"海东地区",
                "addrFullname":"青海省海东地区",
                "addrType":1
            },
            {
                "addrCodeId":"632200",
                "addrName":"海北藏族自治州",
                "addrFullname":"青海省海北藏族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"632300",
                "addrName":"黄南藏族自治州",
                "addrFullname":"青海省黄南藏族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"632500",
                "addrName":"海南藏族自治州",
                "addrFullname":"青海省海南藏族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"632600",
                "addrName":"果洛藏族自治州",
                "addrFullname":"青海省果洛藏族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"632700",
                "addrName":"玉树藏族自治州",
                "addrFullname":"青海省玉树藏族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"632800",
                "addrName":"海西蒙古族藏族自治州",
                "addrFullname":"青海省海西蒙古族藏族自治州",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"640000",
        "addrName":"宁夏回族自治区",
        "addrFullname":"宁夏回族自治区",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"640100",
                "addrName":"银川市",
                "addrFullname":"宁夏回族自治区银川市",
                "addrType":1
            },
            {
                "addrCodeId":"640200",
                "addrName":"石嘴山市",
                "addrFullname":"宁夏回族自治区石嘴山市",
                "addrType":1
            },
            {
                "addrCodeId":"640300",
                "addrName":"吴忠市",
                "addrFullname":"宁夏回族自治区吴忠市",
                "addrType":1
            },
            {
                "addrCodeId":"640400",
                "addrName":"固原市",
                "addrFullname":"宁夏回族自治区固原市",
                "addrType":1
            },
            {
                "addrCodeId":"640500",
                "addrName":"中卫市",
                "addrFullname":"宁夏回族自治区中卫市",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"650000",
        "addrName":"新疆维吾尔自治区",
        "addrFullname":"新疆维吾尔自治区",
        "addrType":0,
        "children":[
            {
                "addrCodeId":"650100",
                "addrName":"乌鲁木齐市",
                "addrFullname":"新疆维吾尔自治区乌鲁木齐市",
                "addrType":1
            },
            {
                "addrCodeId":"650200",
                "addrName":"克拉玛依市",
                "addrFullname":"新疆维吾尔自治区克拉玛依市",
                "addrType":1
            },
            {
                "addrCodeId":"652100",
                "addrName":"吐鲁番地区",
                "addrFullname":"新疆维吾尔自治区吐鲁番地区",
                "addrType":1
            },
            {
                "addrCodeId":"652200",
                "addrName":"哈密地区",
                "addrFullname":"新疆维吾尔自治区哈密地区",
                "addrType":1
            },
            {
                "addrCodeId":"652300",
                "addrName":"昌吉回族自治州",
                "addrFullname":"新疆维吾尔自治区昌吉回族自治州",
                "addrType":1
            },
            {
                "addrCodeId":"652700",
                "addrName":"博尔塔拉蒙古自治州",
                "addrFullname":"新疆维吾尔自治区博尔塔拉蒙古自治州",
                "addrType":1
            },
            {
                "addrCodeId":"652800",
                "addrName":"巴音郭楞蒙古自治州",
                "addrFullname":"新疆维吾尔自治区巴音郭楞蒙古自治州",
                "addrType":1
            },
            {
                "addrCodeId":"652900",
                "addrName":"阿克苏地区",
                "addrFullname":"新疆维吾尔自治区阿克苏地区",
                "addrType":1
            },
            {
                "addrCodeId":"653000",
                "addrName":"克孜勒苏柯尔克孜自治州",
                "addrFullname":"新疆维吾尔自治区克孜勒苏柯尔克孜自治州",
                "addrType":1
            },
            {
                "addrCodeId":"653100",
                "addrName":"喀什地区",
                "addrFullname":"新疆维吾尔自治区喀什地区",
                "addrType":1
            },
            {
                "addrCodeId":"653200",
                "addrName":"和田地区",
                "addrFullname":"新疆维吾尔自治区和田地区",
                "addrType":1
            },
            {
                "addrCodeId":"654000",
                "addrName":"伊犁哈萨克自治州",
                "addrFullname":"新疆维吾尔自治区伊犁哈萨克自治州",
                "addrType":1
            },
            {
                "addrCodeId":"654200",
                "addrName":"塔城地区",
                "addrFullname":"新疆维吾尔自治区塔城地区",
                "addrType":1
            },
            {
                "addrCodeId":"654300",
                "addrName":"阿勒泰地区",
                "addrFullname":"新疆维吾尔自治区阿勒泰地区",
                "addrType":1
            },
            {
                "addrCodeId":"659000",
                "addrName":"省直辖行政单位",
                "addrFullname":"新疆维吾尔自治区省直辖行政单位",
                "addrType":1
            }
        ]
    },
    {
        "addrCodeId":"710000",
        "addrName":"台湾省",
        "addrFullname":"台湾省",
        "addrType":0,
        "children":[

        ]
    },
    {
        "addrCodeId":"810000",
        "addrName":"香港特别行政区",
        "addrFullname":"香港特别行政区",
        "addrType":0,
        "children":[

        ]
    },
    {
        "addrCodeId":"820000",
        "addrName":"澳门特别行政区",
        "addrFullname":"澳门特别行政区",
        "addrType":0,
        "children":[

        ]
    }
]

export default city